version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports: 
      - 8000:8000    
    environment:
      - DATA_DRAKE_AUTH_TOKEN=YOUR_AUTH
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.frontend
  #   ports: 
  #     - 3000:8000  
  #   restart: unless-stopped

networks:
  zoomerfuel_network:
    driver: bridge