version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports: 
      - 8000:8000    
    environment:
      - DATA_DRAKE_AUTH_TOKEN=ZzIJzFieGiBXwFgsiNYknNLbGJVDsQ
    restart: unless-stopped
    volumes: 
      - ./database:/app/backend/database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    network_mode: host 
    # ports: 
    #   - 4173:4173  
    restart: unless-stopped

# networks:
#   zoomerfuel_network:
#     driver: bridge